In [1]:
import numpy as np

from non_linear.first_order.conjugate_gradient import ConjugateGradient
from non_linear.first_order.gradient_descent import GradientDescent
from non_linear.second_order.newton import Newton
from non_linear.second_order.BFGS import BFGS
from non_linear.first_order.accelerated_GD import AcceleratedGD
from non_linear.first_order.steepest_descent import SteepestDescent

from scipy.optimize import line_search, rosen, rosen_der, rosen_hess, minimize

def obj_fun(x):
    return np.array(rosen(x))

def obj_grad(x):
    return np.array(rosen_der(x))

def obj_hess(x):
    return np.array(rosen_hess(x))

In [11]:
x0 = np.random.randn(10)*1 + 2
eps0 = 10**-2
eps = 10**-4
eps2 = 10**-8
k_lim = 3*10**4


In [35]:
x = GradientDescent.solve(obj_fun, obj_grad, x0, eps0, k_lim*2)
x

k = 59999


array([1.00140553, 1.00281928, 1.00566216, 1.01138924, 1.02297458,
       1.04660936, 1.09565225, 1.20095977, 1.443252  , 2.08464066])

In [36]:
x = AcceleratedGD.solve(obj_fun, obj_grad, x0, eps0, k_lim // 3)
x

k = 9999


array([1.00083272, 1.00166966, 1.00335091, 1.00673156, 1.0135459 ,
       1.02735024, 1.05559731, 1.11457784, 1.24284528, 1.54569992])

In [12]:
x = SteepestDescent.solve(obj_fun, obj_grad, x0, eps, k_lim)
x

k = 15724


array([1.00000025, 1.00000049, 1.00000102, 1.000002  , 1.00000405,
       1.00000807, 1.00001623, 1.00003249, 1.00006518, 1.00013067])

In [37]:
x = ConjugateGradient.PolakRibier(obj_fun, obj_grad, x0, eps, k_lim)
x

k = 12355


array([1.00000025, 1.00000052, 1.00000101, 1.00000207, 1.0000041 ,
       1.00000827, 1.00001654, 1.0000332 , 1.00006654, 1.00013343])

In [38]:
x = ConjugateGradient.FletcherReeves(obj_fun, obj_grad, x0, eps, k_lim)
x

k = 1733


array([1.00000023, 1.00000035, 1.00000065, 1.00000134, 1.0000027 ,
       1.00000548, 1.00001089, 1.00002176, 1.00004365, 1.00008755])

In [32]:
x = BFGS.solve(obj_fun, obj_grad, x0, eps2, k_lim//100)
x

k = 70


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
x = Newton.solve(obj_fun, obj_grad, obj_hess, x0, eps2, k_lim//200)
x

k = 14


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])